### ISSUE TITLE
No module named 'adidt.utils'

### ISSUE THREAD

**Issue by CBellmann-HTEC** [analogdevicesinc/pyadi-dt#24]
Hello,
when executing adidtc, i get the following error message:
`
Traceback (most recent call last):
  File "/usr/local/bin/adidtc", line 5, in <module>
    from adidt.cli.main import cli
  File "/home/analog/.local/lib/python3.9/site-packages/adidt/__init__.py", line 6, in <module>
    from adidt.parts.adrv9009 import adrv9009_dt
  File "/home/analog/.local/lib/python3.9/site-packages/adidt/parts/adrv9009.py", line 4, in <module>
    from adidt.utils import profilewiz, tes
ModuleNotFoundError: No module named 'adidt.utils'
`
I cant find adidt.utils, shouldnt it be included in the package?
Best regards,
Christoph

**Comment by CBellmann-HTEC** [comment]
Hello Travis,

i installed it as advised via: ` pip install git+https://github.com/analogdevicesinc/pyadi-dt.git`
Running it again shows following output:
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/analogdevicesinc/pyadi-dt.git
  Cloning https://github.com/analogdevicesinc/pyadi-dt.git to /tmp/pip-req-build-qpln7tgh
  Running command git clone -q https://github.com/analogdevicesinc/pyadi-dt.git /tmp/pip-req-build-qpln7tgh
Requirement already satisfied: Click in /usr/lib/python3/dist-packages (from adidt==0.0.1) (7.1.2)
Requirement already satisfied: bcrypt==3.2.2 in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (3.2.2)
Requirement already satisfied: fabric in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (3.2.2)
Requirement already satisfied: fdt in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (0.3.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (1.26.2)
Requirement already satisfied: rich in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (13.7.0)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.9/dist-packages (from adidt==0.0.1) (0.13.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.9/dist-packages (from bcrypt==3.2.2->adidt==0.0.1) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.1->bcrypt==3.2.2->adidt==0.0.1) (2.21)
Requirement already satisfied: deprecated>=1.2 in /usr/local/lib/python3.9/dist-packages (from fabric->adidt==0.0.1) (1.2.14)
Requirement already satisfied: paramiko>=2.4 in /usr/local/lib/python3.9/dist-packages (from fabric->adidt==0.0.1) (3.3.1)
Requirement already satisfied: decorator>=5 in /usr/local/lib/python3.9/dist-packages (from fabric->adidt==0.0.1) (5.1.1)
Requirement already satisfied: invoke>=2.0 in /usr/local/lib/python3.9/dist-packages (from fabric->adidt==0.0.1) (2.2.0)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/lib/python3/dist-packages (from deprecated>=1.2->fabric->adidt==0.0.1) (1.12.1)
Requirement already satisfied: cryptography>=3.3 in /usr/lib/python3/dist-packages (from paramiko>=2.4->fabric->adidt==0.0.1) (3.3.2)
Requirement already satisfied: pynacl>=1.5 in /usr/local/lib/python3.9/dist-packages (from paramiko>=2.4->fabric->adidt==0.0.1) (1.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.9/dist-packages (from rich->adidt==0.0.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.9/dist-packages (from rich->adidt==0.0.1) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.9/dist-packages (from markdown-it-py>=2.2.0->rich->adidt==0.0.1) (0.1.2)
```
Best,
Christoph

**Comment by alexeykosinov** [comment]
Hello, 
same error (debian)

**Comment by tfcollins** [comment]
Can you provide the cli command or python snippet, if used as a module, which causes the issue?

**Comment by alexeykosinov** [comment]
Yeah, sure!
I use VScode remote that connects to the debian server:

VSCode extensions:
Jupyter v2024.1.1
Python v2024.0.1

Python version 3.9.2
Jupiter:
> Selected Jupyter core packages...
> IPython          : 8.18.1
> ipykernel        : 6.29.2
> ipywidgets       : not installed
> jupyter_client   : 8.6.0
> jupyter_core     : 5.7.1
> jupyter_server   : not installed
> jupyterlab       : not installed
> nbclient         : not installed
> nbconvert        : not installed
> nbformat         : not installed
> notebook         : not installed
> qtconsole        : not installed
> traitlets        : 5.14.1

If i run it with jupiter ad9081_rxtx_example.ipynb from [pyadi-jif](https://github.com/analogdevicesinc/pyadi-jif) see attached log

Or standalone:
> Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import adidt
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/deb/.local/lib/python3.9/site-packages/adidt/__init__.py", line 6, in <module>
>     from adidt.parts.adrv9009 import adrv9009_dt
>   File "/home/deb/.local/lib/python3.9/site-packages/adidt/parts/adrv9009.py", line 4, in <module>
>     from adidt.utils import profilewiz, tes
> ModuleNotFoundError: No module named 'adidt.utils'
> >>> 

Hope it helps!
[jupiter_log.txt](https://github.com/analogdevicesinc/pyadi-dt/files/14369205/jupiter_log.txt)

**Comment by tfcollins** [comment]
Fix should be available nowadays

**Comment by alexeykosinov** [comment]
Thanks!

**Comment by CBellmann-HTEC** [comment]
Hi,
thanks a lot!
Sorry, i dont get where to pull the fix, i am looking at the branches to find it.

**Comment by CBellmann-HTEC** [comment]
Hi, thanks, its working!
